# Use official NGINX image from Docker Hub
FROM nginx:latest

# Copy the custom NGINX configuration file into the container
RUN rm /etc/nginx/conf.d/nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to access the NGINX server
EXPOSE 80

# Command to run NGINX
CMD ["nginx", "-g", "daemon off;"]
