apiVersion: v1
kind: Service
metadata:
  name: capital-gains-service
  namespace: myapp
spec:
  selector:
    app: capital-gains
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
