apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: myapp
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongodb"