apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: myapp
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30017
  type: NodePort